### ISSUE TITLE
make payment within 0.7 backward compatible with 0.6

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#1331]
Why:
- not to struggle with communication on incompatibility
- make both version cooperate 

What:
- support both GSB protocols

**Comment by maaktweluit** [comment]
Turns out making this feature "optional" is the same as removing the whole feature.
When providers accept payments without signature there is no need for the signature.

I propose to:
- Split the router for 0.7 ( or another "network split" )
- Revert the feature on 0.7 and apply it to 0.8 where the SB will be upgraded
