### ISSUE TITLE
Consider running commands in shell inside vm

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1351]
Why:
- Developer must use full binaries path (PATH variable not available)

What:
- Consider if we should run commands in shell
- Possibly use default shell from Docker image

**Comment by mfranciszkiewicz** [comment]
Running commands in shell assumes that:
- we always want to execute commands inside the shell, never via `exec`
- there is a shell binary available inside the image
- we can resolve which shell binary to use (e.g. by reading the `/etc/passwd` file)
- the shell binary inside `/etc/passwd` is the one the developer wants to use

all of which would have to be done by `init`. This would make the VM runtime more opinionated instead of keeping it as generic as possible. 

Instead of making assumptions of what developers want, we can give them a better API. This issue is easily solved on the SDK side - e.g., each `ctx.run` could be wrapped within `bash -c` by default. There could also be an option to change the shell binary or to simply `exec` commands.

Considering that it's less constraining and time-efficient to do this in SDK, I'm closing this issue.
