### ISSUE TITLE
Debit note acceptance arrives before .send() returns

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna#1373]
Why: From provider agent perspective this behaviour is  unexpected and may lead to bugs.
What: It's possible to receive a `DebitNoteAccepted` event before finishing `PaymentAPI.send_debit_note()` call.

Full logs & discussion are available in #1333 . #1372 prepares current provider agent implementation for this situation, but the bug may reappear if we expect to have custom provider implementations in the future.

**Comment by maaktweluit** [comment]
After investigation there are 2 places where this can go wrong:
- when "SendDebitNote" message times out ( but is partially handled on the receiving side ) https://github.com/golemfactory/yagna/blob/master/core/payment/src/api/debit_notes.rs#L213
- when mark_received() is unable to get a quick lock on the database https://github.com/golemfactory/yagna/blob/master/core/payment/src/api/debit_notes.rs#L218

This seems to be a more common problem in yagna where the states between 2 nodes are not in sync. This does not occur when following the happy-path, but only when timeouts happen or locks are not available when expected.
This problem is also known as "the 2 generals problem".

Will post the rest of my research in a next comment

**Comment by maaktweluit** [comment]
When communicating between different nodes in the golem network there is an uncertainty if messages are arriving properly.

On happy-path scenario's this goes well, but we need to be resilient to these un-happy scenario's as well:

1. Message send, lost before arrival ( no state changed, sender gets error)
2. Message send, timeout before Ack, leaving 3 possible states:
  a. Receiver did not handle the message ( same as case 1 )
  b. Receiver partially handled the message ( state out of sync: receiver partially updated, sender failed )
  c. Receiver fully handled the message ( state out of sync: receiver updated, sender failed )
3. Message send AND Ack received, sender hanging after Ack. ( state out of sync: receiver updated, sender too late)

All of these cases could be fixed with re-try and proper handling of the incorrect state.

Possible solutions for debit-note send() issue:
- lock the connection with this node ( only solves point 3 )
- mark received before sending remote call ( needs work for re-try )
- Actively re-try the call ( does not solve point 3 )
- decouple "/send_debit_note" from sending "SendDebitNote":
  - api call will mark debit note as ready to be send
  - background job will send "SendDebitNote" till:
    - debit note received properly
    - timeout expires

Honestly i do not like the solutions proposed above, maybe @tworec, @mfranciszkiewicz or @prekucki can have a look and add their 2 cents?

**Comment by prekucki** [comment]
`/send_debit_note` should be send by background job but without retries. provider is responsible to track if a timeout occurs.

**Comment by cryptobench** [comment]
[nohup.out.zip](https://github.com/golemfactory/yagna/files/7143093/nohup.out.zip)

Example from a provider over on Discord.

You can grep for this line  `ya_provider::tasks::task_manager] Breaking agreement [d66938e3d8f77da56c5b8628d0d6f6c816c003692b8c8f8b5184c20d37c84f87], reason: Requestor is unreachable more than 4m.`

**Comment by evik42** [comment]
@nieznanysprawiciel is it still a valid problem to look into or related to older versions only?

**Comment by golmek** [comment]
Closing ticket as not moved for more than 1 year.
