### ISSUE TITLE
Resuming services

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1692]
Why:
- Services must be able to start working after update without breaking Agreement

What:
- [x] #1697

Tasks:
- [x] #1778
- [x] #1779
- [x] https://github.com/golemfactory/ya-runtime-sdk/issues/20
- [x] #1780
- [ ] https://github.com/golemfactory/yapapi/issues/799 (SDK team)

**Comment by mfranciszkiewicz** [comment]
## Implementation tasks for service resuming / restarting

In order to provide computing resources on Golem, several yagna-ecosystem
processes need to be running simultaneously. In order to snapshot the
computation state, we must allow for all components to shutdown gracefully.
E.g., a planned system restart needs to wait for termination of all
components and should use SIGKILL as a last resort.

### ya-exe-unit

Because ExeUnit or Runtime suspension / restoration may take a substantial amount
of disk space or time, it's recommended to separate it from the (graceful)
process shutdown; i.e., while terminating the process, no state is persisted
to disk. This behavior is also undesirable when an Agreement needs to be
terminated.

The suspension may be triggered in following ways:

a. REST yagna endpoint for suspending the ExeUnit
b. sending to and handling a `USR1` or `USR2` signal by the ExeUnit
  (not compatible with Windows)
c. extending `ya-runtime-api` with an interface to control the ExeUnit

Tasks:

- bind and implement a GSB handler for **entering a new `Suspended` state**
  - pause the following:
    - next command execution
    - output streaming
    - VPN communication
    - internal usage counter updates (optional)
  - await current command termination (with a short timeout)
  - set the state to `(Ready, Some(Suspended))`
  - in background, the ExeUnit snapshots its state:
    - counter values
    - `ExeScript`s
    - command execution state (outputs, return code)
    - VPN state (e.g. node neighborhood)
  - when snapshot serialization is complete, ExeUnit waits for runtime
    process termination
  - set the state to `(Suspended, None)`
  - shutdown ExeUnit

- automatically restore ExeUnit state from the snapshot, if found in the working
  directory; command execution is resumed if some batch wasn't completed

- rule of thumb: runtime process dies second

### ya-runtime-api

- new: `RuntimeService::suspend`
  - Client: triggers runtime suspension; called by ExeUnit
  - Server: implemented by the runtime; it's expected to snapshot
    its state and halt the process. The call may be facilitated by
    `ya-runtime-sdk`

- new: `Suspend` protobuf message
  Used by the `suspend` RPC call.

### ya-runtime-sdk

- rule of thumb: runtime process dies first

- runtime implementation ignores SIGTERM (so that only
  `RuntimeService::shutdown` is used for graceful termination)

- new: `Runtime::suspend`
  For implementing the snapshotting and halting mechanism.

  The expected behavior is to only snapshot the state when idle,
  i.e., when no ExeScript command is running. Running commands should
  be cancelled after a brief wait time period.

  Provides default implementation for serializing a basic state
  `struct` / `enum`, if set via `RuntimeDef` macro attribute.

- extend `ya-runtime-sdk-derive`'s `RuntimeDef` derive macro to
  set a custom state type and an option for disabling startup
  state auto-restoration

- restoration of the serialized state while starting the runtime,
  if the files can be found in the working directory (`workdir`)

### ya-provider

- rule of thumb: this process dies one before last

- on agent process shutdown, use the Activity API REST endpoint to suspend
  running activities and await the termination of ExeUnit(s)
  - do not manually set the `Terminated` state via Activity API
  - (optional) stop sending debit notes
  - (optional) stop the activity state monitor

- on start, fetch suspended activities via Activity API
  - skip activities not matching the active subnet, payment methods
    and hardware resource caps
  - ignore restored activity debit note acceptance timeout
  - resume activities, i.e. start ExeUnit(s) in previous working directories

#### yagna

- rule of thumb: this process dies last

- new: Activity API endpoints:
  - activity suspension
  - suspended activity list

- assert that each Activity API endpoint has an associated default timeout

#### yapapi, yajsapi

In general, the SDKs need to be aware that some remote GSB calls may timeout
due to suspension of the ExeUnit / Runtime. The implementation needs to fetch
and react to the current activity state.
Additionally, the SDKs should rely on the timeouts built-in the Activity API
to provide future-proof compatibility with prolonging calls due to suspension.

- ignore timeouts on remote GSB calls (e.g. `GetExecBatchResults`) when
  the activity is entering or entered the `Suspended` state

- pause / ignore errors in all agreement-breaking cyclic jobs when the
  activity is `Suspended`
  - resume those jobs when the activity state changes from
    `Suspended` to `Terminated` or `(Ready, _)`

**Comment by maaktweluit** [comment]
Nice overview!

One thing to add is that on yagna start-up the resuming of activities need to be triggered after payments have been initiated

**Comment by jiivan** [comment]
> Nice overview!
> 
> One thing to add is that on yagna start-up the resuming of activities need to be triggered after payments have been initiated

So probably payment initiation should be permanent without the need to do this on every run.

**Comment by nieznanysprawiciel** [comment]
> pause the following:
>    output streaming

We should pause after command stop executing (either successfully or with timeout). Requestor still wants to get full stream

**Comment by nieznanysprawiciel** [comment]
> resume activities, i.e. start ExeUnit(s) in previous working directories
We need to restore whole Provider state for whole Agreement.

**Comment by nieznanysprawiciel** [comment]
@mfranciszkiewicz Can you propose and create tasks for this feature? This was part of the reasearch

**Comment by mfranciszkiewicz** [comment]
> > pause the following:
> > output streaming
>
> We should pause after command stop executing (either successfully or with timeout). Requestor still wants to get full > > stream

The next point states `await current command termination (with a short timeout)`

**Comment by nieznanysprawiciel** [comment]
> > > pause the following:
> > > output streaming
> > 
> > 
> > We should pause after command stop executing (either successfully or with timeout). Requestor still wants to get full  stream
> 
> The next point states `await current command termination (with a short timeout)`

I meant that order is wrong. First we need to wait and than pause
