### ISSUE TITLE
Add a provider command to list payments going into this specific node.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/yagna#1770]
Some of the providers has multiple nodes under the same wallet, and it's impossible to differentiate where these transactions came from on the blockchain itself. So providers are asking for some kind of command to list the latest `n` payments that went into this specific node they're running.

**Comment by nieznanysprawiciel** [comment]
@cryptobench Why do they need this? Is this only curiosity or do they have specific needs?
Are they interested in matching between transactions and Agreements (or Invoices) or they need to know only the amount of money?

This may be related: https://github.com/golemfactory/yagna/issues/1660
Do you think it would solve their problem? or maybe we can extend the tasks above?
Why do they need `n`-latest instead of relying on date?

**Comment by pwalski** [comment]
Closing because there has been no response and #1660 provides some solution
(cmdline `yagna payment status --driver erc20 --network polygon --last 1week --json`)
