### ISSUE TITLE
Include outbound net allowed domains whitelist in release

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2105]
Why:
- [x] We want to provide our default whitelist

What:
- [x] Create allowed domains list (maybe ask @prekucki )
- [x] Update installer to install whitelist
- [ ] Decide what should installer do, in case Provider modified his whitelist

related: https://github.com/golemfactory/yagna/issues/2082

**Comment by pwalski** [comment]
Regarding
>  "Decide what should installer do, in case Provider modified his whitelist" 

installer does not have many options. It can either:
- skip adding default domains to whitelist
- add default domains to whitelist (it will not cause duplicates)

For now I decided to always add default domains to whitelist because:
- it was an easier path
- it is a first release of Provider with whitelist, so the question of what to do with modified whitelist can be answered during next release
