### ISSUE TITLE
VPN host is unreachable

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#2149]
Occurring while executing `ya-perf`:

```
[2022-08-05T15:49:55.460+0200 INFO yapapi.utils] Error: Command 'Run /bin/bash ('-c', 'scp -v /golem/dummy.dat root@192.168.0.7:/golem/upload')' failed on provider; message: 'ExeScript command exited with code 1'; stderr: 'Executing: program /usr/bin/ssh host 192.168.0.7, user root, command scp -v -t /golem/upload
OpenSSH_8.8p1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to 192.168.0.7 [192.168.0.7] port 22.
debug1: connect to address 192.168.0.7 port 22: Host is unreachable
ssh: connect to host 192.168.0.7 port 22: Host is unreachable
lost connection
'
```

**Comment by wkargul** [comment]
This log from above came from execution of exe script. This is something what `scp` tool (running in background for VPN transfer test) produces as the output when host is unreachable.

It means that the client node was trying to connect to the host node (192.168.0.7) but failed. This is the effect of node beeing unable to connect but it is not indicating any specific bug by itself. Sometimes node may be disconnected due to network problems so we expect to observe such logs. 

Likely in this particular situation disconnection is caused by timeouts or any other known issue adressed under tasks:
- https://github.com/golemfactory/ya-relay/issues/197
- https://github.com/golemfactory/yagna/issues/2148
