### ISSUE TITLE
Come up with other solutions proposals for improving vpn performance

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna#2212]

**Comment by mfranciszkiewicz** [comment]
- GSB bi-drectional channel feature
  
  A new flavour of communication flow, where both communicating sides can send and receive multiple messages. Implemented as an extension to the existing GSB protocol, introduces messages for (un)registering a new type of service (handler), connecting to or disconnecting from a channel and data messages. Requires extra helper functions for binding services of the new kind and also functions for calling these services.

  Channel exclusivity, where only a single client is allowed, will be controlled by the end-service alone.
  
- GSB streaming feature refactored into bi-directional streams  

  Re-uses the existing protocol (with minor / fewer extensions than in the previous point) and messages while changing the behaviour of the currently implemented streaming feature. The behaviour would be changed to accept multiple request messages while generating a single response stream, instead of a response stream per request message.

  Currently used in a single scenario, where ExeUnit output is streamed back to the caller.

- GSB no response endpoints

  Introduces a special case of a GSB call where it would not trigger sending a response. Would require for both sides to bind a service for receiving GSB calls for creating two-way communication, while agreeing on the exposed service addresses beforehand.

- extra GSB socket

  A separate (UDP) socket, handling exclusively the bi-drectional channel protocol.

**Other possibilities:**

- Hybrid NET direct VPN socket communication

  As implemented in https://github.com/golemfactory/yagna/issues/2210 / https://github.com/golemfactory/yagna/pull/new/mf/vpn-optim 

- Hybrid NET direct channels

  An alternative to GSB communication, where VPN packets are redirected to a (remote) socket exposed by the hybrid net service by the ExeUnit. An appropriate call to hybrid net's vpn service would be required to set up such socket.
