### ISSUE TITLE
Rinkeby invoices when mainnet invoices are expected

### ISSUE THREAD

**Issue by johny-b** [golemfactory/yagna#2272]
### WHAT HAPPENS ###

1. I initialize both `mainnet` and `rinkeby` payments in `yagna`
2. I create an `erc20-mainnet-glm` allocation
3. I publish demand to the `public-beta` subnet
4. I trade with providers who only accept `mainnet` payments
5. Providers issue invoices for `erc20-rinkeby-tglm` payments (!)
6. I accept the invoices using my `erc20-mainnet-glm` allocation (!)
7. The amount of my `mainnet` GLMs stays the same. The amount of my `rinkeby` GLMs decreases.

### HOW TO REPLICATE ###

1. Install https://github.com/golemfactory/golem-api-python
2. ` YAGNA_PAYMENT_NETWORK=mainnet YAGNA_SUBNET=public-beta python3 blender.py` (wait for a successful finish, ctrl+c might break invoice acceptance).
3. Observe how `yagna payment status` and `yagna payment status --network=mainnet` change

OR

Probably the same will happen in `yapapi` if we remove the line that sets `demand_builder.properties["golem.com.payment.chosen-platform"]` - although I didn't check this.

### PROBLEMS ###

There are (at least) two separate problems here that probably should be separate issues, but I think there might be some general problem I'm missing here so they are together:

* [ ] Why do providers send `rinkeby` invoices when demand specifies a `mainnet` allocation and also they only accept `mainnet` payments?
* [ ] Why am I allowed to accept a `rinkeby` invoice using a `mainnet` allocation?

**Comment by johny-b** [comment]
> In https://github.com/golemfactory/yagna/blob/2f6efcd5e1e5959a05effa6192c9ae31f11d5f42/core/payment/src/models/agreement.rs line 42, yagna uses default platform if `golem.com.payment.chosen-platform` doesn't exist in Agreement -> it is a bug

Does this explain why I can accept the invoice using a mainnet allocation?

**Comment by mateuszsrebrny** [comment]
@nieznanysprawiciel decide please :)

**Comment by nieznanysprawiciel** [comment]
This bug seems important.
We should do it this sprint or next.

> Does this explain why I can accept a rinkeby invoice using a mainnet allocation?
Doesn't. It's separate bug

**Comment by evik42** [comment]
might be related: #1753

**Comment by mateuszsrebrny** [comment]
the way I see it, there is a separate issue https://github.com/golemfactory/golem-core-python/issues/18 that golem-core is not setting the property -> this is to be fixed by golem-core care takers.

but in yagna there is a bug that it sends rinkeby when the property is not set.
(and maybe that requestor accepts the invoice (not sure if this is still in yagna or in in golem-core)

from pov of ray project the bug in yagna is less important (as long as setting the property would be enough :)

**Comment by golmek** [comment]
**Summary:**

When using Golem Core Python (https://github.com/golemfactory/golem-core-python) Rinkeby is used as a payment network even tough mainnet was explicitly chosen. This is due to lack of _**golem.com.payment.chosen-platform**_ property in Golem Core Python and will be fixed in: https://github.com/golemfactory/golem-core-python/issues/18 

However, current behaviour of Yagna is prone to errors as we accept lack of  _**golem.com.payment.chosen-platform**_  parameter and then choose default -> Rinkeby. This results in hard to debug problems when testnets are not stable or getting deprecated (like Rinkeby).

New approach should require this parameter and throw error when it is missing. No default path.

**Acceptance Criteria:**

- Lack of _**golem.com.payment.chosen-platform**_   should throw explicit error.
- Disable default path for situation when there is no _**golem.com.payment.chosen-platform**_

**Comment by golmek** [comment]
Closing this ticket as it is not replicable anymore after Golem Core Python was fixed by @approxit .

Changes in Yagna will be performed in separate ticket: https://github.com/golemfactory/yagna/issues/2639
