### ISSUE TITLE
Plan test scenario for outbound feature

### ISSUE THREAD

**Issue by wkargul** [golemfactory/yagna#2295]
- [x] prepare testing scenario for outbound feature
- [x] contact with Release team and make them aware of it

**Comment by pwalski** [comment]
I have prepared scenario for Outbound Net - https://www.notion.so/golemnetwork/requestor-testing-session-2-outbound-b5099b11d3364092a3a81696a91996c0?p=5696bbddbd3e48389ed2f1ce24b71184&pm=s 

Also first scenario, `handbook setup`, got updated with command to clone a sample project.
For now it will be a branch of https://github.com/golemfactory/provider-network-benchmarks/tree/test_session_examples

Scenario mentions that only “sharkoon_378.h” and “qbam.h” will respond, because I added there default certificates and one of our whitelisted domains.
