### ISSUE TITLE
try running goth on new runners

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna#2456]

**Comment by etam** [comment]
What to do:
- In files `.github/workflows/integration-test-*.yml` replace
  - runner label
    ```patch
    -runs-on: [goth, ubuntu-18.04]
    +runs-on: [goth, ubuntu-22.04]
    ```
  - python version
    ```patch
       - name: Configure Python
         uses: actions/setup-python@v2
         with:
    -      python-version: "3.8.0"
    +      python-version: "3.10.0"
    ```
  - everything else is unknown

**Comment by golmek** [comment]
Error: 
![image](https://user-images.githubusercontent.com/126684244/230023409-44752970-c102-4782-b9b7-d3b5195535e7.png)

@Smokowski will check with SDK first

**Comment by nieznanysprawiciel** [comment]
Since we weren't able to find the cause of this problem and we can't spend more time on this in this quarter, we will make a decision before planning Q3, how to proceed.

**Comment by golmek** [comment]
Moving from In Progress -> Ready as it will be re-visited before Q3

**Comment by jalas167** [comment]
comments and history of resolutino attempts are in https://github.com/golemfactory/yagna/pull/2534

**Comment by evik42** [comment]
I am looking into this.

**Comment by evik42** [comment]
My findings:
- Even after changing docker network from default to a named one to be able to disable ipv6, mitmproxy is not serving connections
- The routing addon in mitmproxy is not called, the connection is lost before that
- Tried to upgrade mitmproxy as v5.3 is 3 years old, unfortunately they do not support running mitmproxy embedded into a python application since 7.0 (latest version is 9.0.1)
  - This is causing problem with signal registration, I tried to monkey patch it but did not succeed
  - Tried to run mitmproxy in a separate process, it starts up but does not forward traffic
- `actions/setup-python@v4` can install Python 3.8 to Ubuntu 22.04, tried that also did not change a thing
  
 I am not a python expert so maybe I missed something but I was not able to make it work.
