### ISSUE TITLE
Testing: Negotiations

### ISSUE THREAD

**Issue by MrDarthShoe** [golemfactory/yagna#2576]
https://github.com/golemfactory/yagna/issues/2543
Test exploratively: try to break things via CLI, misbehaving tests, anything.

**Comment by pwalski** [comment]
Finding:
When verifying _Audited Payload_ signed by X.509 cert `C` (which is part of chain `A->B->C`) checking _Rules_ starts from `C` downward, instead of `B` (like it has been done in case of old implementation of `Permission`s).
I believe it is not a problem. 
Theoretically `C` could be used for signing both data and another certificate (`D`), but in such case it will not seem weird when Provider with _Rule_ set for `C` will check this _Rule_ on arrival of _Audited Payload_  signed by `C`.
If above is ok, then I only need to open PR changing this comment https://github.com/golemfactory/yagna/blob/302baa6088a9e3e1cabc35d3fb3a2147852e10ef/utils/manifest-utils/src/keystore.rs#L150

**Comment by evik42** [comment]
It is intentional to check the leaf first (C) and then go up the chain. The first certificate that matches a rule determines the rules for that payload.
It should be the same for partner rules, but please check.
