### ISSUE TITLE
Cleanup Rinkeby traces from Yagna after 0.12.2 release

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#2638]
After Yagna 0.12.2 default testnet is set to Goerli. Rinkeby was deprecated and is not existing anymore.
We should check and cleanup all references to Rinkeby in Yagna codebase.

**Acceptance Criteria:**

- Find all references to Rinkeby network in Yagna Codebase  
   - Verify what they are doing & Remove them / Switch fo Goerli
- Yagna should be working correctly with Goerli as a default testnet and without any trace of Rinkeby in the codebase
 - **QUESTION** do we need to make additional release with these changes (as for now, @jiivan  says that yagna doesn't work without Rinkeby)? 

**Additional Information:**

- Example of the problem:
   -   https://github.com/golemfactory/yagna/blob/master/core/payment-driver/erc20/src/erc20/wallet.rs#L38
   - https://github.com/golemfactory/yagna/blob/master/core/payment-driver/erc20/src/erc20/wallet.rs#L76

**Comment by nieznanysprawiciel** [comment]
Additional things:
- We need to set correctly default payment accounts
   - `goerli` account
   - `polygon` mainnet account

Not having payment account initialized requires using later `yagna payment init` in yapapi/yajsapi.
yagna should initialize account during making allocation, but the problem is, that SDK reads list of accounts first to determine if it should allow to make this allocation.
This points to deeper problem with accounts idea which must be reconsidered during future works on payments.

**Comment by golmek** [comment]
@staszek-krotki Can You share a status of this ticket?

**Comment by staszek-krotki** [comment]
Defaults have been changed so that rinkeby is not used as a default anymore but it is still supported. There needs to be a deeper refactoring of payment drivers that will remove any hardcoded networks from them but that's paused for now
