### ISSUE TITLE
yagna spams web3 endpoint with queries

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#2642]
Version 0.12.2

It repeats
```
INFO  ya_erc20_driver::driver::cron] Transaction not found on chain
WARN  ya_erc20_driver::driver::cron] Transaction not found on chain for Some(2023-06-22T14:28:21.537235142)
WARN  ya_erc20_driver::driver::cron] Time since last action Duration { secs: 501534, nanos: 488962350 }
```

100% reproducible with this datadir: https://drive.google.com/file/d/1Gn_0kGfGzu_5f22rHHB8fsL8oyMSn_aS/view?usp=sharing

**Comment by nieznanysprawiciel** [comment]
What endpoint is spammed?
How often is query made?
From the logs is seems that transaction is retried, because for some reason it couldn't be send on blockchain. What is the expected action instead? Because I assume that we want to retry, so the behavior seems correct.
Maybe it happens too often?
Anyway it seems that underlying problem is completely different

**Comment by etam** [comment]
Yeah, I think I was a bit overreacting. The high amount of logs seems to be related to amount of transactions that were made. Apart from that the logs seems ok.
