### ISSUE TITLE
Fix problem with not paying AR

### ISSUE THREAD

**Issue by golmek** [golemfactory/yagna#3014]
As reported by Devops AR with new payment driver stopped paying. We need to verify this and fix the problem

**Acceptance Criteria:**
- Fix problem with AR

**Comment by kamirr** [comment]
The ARs aren't paying because they aren't doing any work. I grepped all logs of drone 0, and the last mention of an agreement has been January 11, which is consistent with [recorded transactions](https://polygonscan.com/address/0xdd329f6edf93637634e8862d34c3909d298a7055#tokentxns).

I did not find any issues pertaining to negotations either. I don't know how to debug an issue with AR not attempting to make requests, will ask with jiivan.

**Comment by golmek** [comment]
Darek is back on monday (29.01.2024)

**Comment by golmek** [comment]
- Verify if any AR works on our RC - @golmek 
- version to test: [v0.15.0-rc15 #388](https://github.com/golemfactory/yagna/releases/tag/pre-rel-v0.15.0-rc15)
- run for few days on AR with our own Providers

**Comment by golmek** [comment]
- drone 0: pre-rel-v0.15.0-rc10 - not paying for 10 days
- drone 1: yagna 0.14 - OK
- drone 2: yagna 0.14 - not paying for 10 days

**Comment by golmek** [comment]
AR works - closing ticket.
